Repository markcheret/footnotes, pull requests merged in 2021-02, with the labels that each got.

#2 Create README.md
  README.md
  img/footnotes.png
Labels: documentation

#1 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#3 Generate documentation
  .gitignore
  docs/classes/MCI-Footnotes-Config.html
  docs/classes/MCI-Footnotes-Convert.html
  docs/classes/MCI-Footnotes-Hooks.html
  docs/classes/MCI-Footnotes-Language.html
  docs/classes/MCI-Footnotes-Layout-Diagnostics.html
  docs/classes/MCI-Footnotes-Layout-Init.html
  docs/classes/MCI-Footnotes-Layout-Settings.html
  docs/classes/MCI-Footnotes-LayoutEngine.html
  docs/classes/MCI-Footnotes-Settings.html
  docs/classes/MCI-Footnotes-Task.html
  docs/classes/MCI-Footnotes-Template.html
  docs/classes/MCI-Footnotes-WYSIWYG.html
  docs/classes/MCI-Footnotes-Widget-ReferenceContainer.html
  docs/classes/MCI-Footnotes-WidgetBase.html
  docs/classes/MCI-Footnotes.html
  docs/css/base.css
  docs/css/normalize.css
  docs/css/template.css
  docs/files/class-config.html
  docs/files/class-convert.html
  docs/files/class-dashboard-init.html
  docs/files/class-dashboard-layout.html
  docs/files/class-dashboard-subpage-diagnostics.html
  docs/files/class-dashboard-subpage-main.html
  docs/files/class-hooks.html
  docs/files/class-init.html
  docs/files/class-language.html
  docs/files/class-settings.html
  docs/files/class-task.html
  docs/files/class-template.html
  docs/files/class-widgets-base.html
  docs/files/class-widgets-reference-container.html
  docs/files/class-wysiwyg.html
  docs/files/footnotes.html
  docs/files/includes.html
  docs/graphs/classes.html
  docs/index.html
  docs/indices/files.html
  docs/js/search.js
  docs/js/searchIndex.js
  docs/namespaces/default.html
  docs/packages/Default.html
  docs/packages/default.html
  docs/reports/deprecated.html
  docs/reports/errors.html
  docs/reports/markers.html
Labels: documentation

#14 Create LICENSE
  LICENSE
Labels: documentation

#4 Create SECURITY.md
  SECURITY.md
Labels: documentation

#25 Update README.md
  README.md
Labels: documentation

#26 Update readme.txt
  readme.txt
Labels: documentation

#27 Update README.md
  README.md
Labels: documentation

#28 Footnotes emphasis
  CONTRIBUTING.md
  README.md
Labels: good first issue

#37 Append line endings
  class/config.php
  class/convert.php
  class/dashboard/init.php
  class/dashboard/layout.php
  class/dashboard/subpage-diagnostics.php
  class/dashboard/subpage-main.php
  class/hooks.php
  class/init.php
  class/language.php
  class/settings.php
  class/task.php
  class/template.php
  class/widgets/base.php
  class/widgets/reference-container.php
  class/wysiwyg.php
  css/dev-common.css
  css/dev-tooltips-alternative.css
  css/dev-tooltips.css
  css/settings.css
  features.txt
  footnotes.php
  includes.php
  js/wysiwyg-editor.js
  license.txt
  readme.txt
  templates/dashboard/customize-css-migration.html
  templates/dashboard/customize-css-new.html
  templates/dashboard/customize-css.html
  templates/dashboard/customize-hyperlink-arrow.html
  templates/dashboard/customize-superscript.html
  templates/dashboard/diagnostics.html
  templates/dashboard/editor-button.html
  templates/dashboard/expert-lookup.html
  templates/dashboard/how-to-donate.html
  templates/dashboard/how-to-help.html
  templates/dashboard/manfisher.html
  templates/dashboard/mouse-over-box-appearance.html
  templates/dashboard/mouse-over-box-dimensions.html
  templates/dashboard/mouse-over-box-display.html
  templates/dashboard/mouse-over-box-position.html
  templates/dashboard/mouse-over-box-text.html
  templates/dashboard/mouse-over-box-timing.html
  templates/dashboard/mouse-over-box-truncation.html
  templates/dashboard/other-plugins.html
  templates/dashboard/settings-excerpts.html
  templates/dashboard/settings-love.html
  templates/dashboard/settings-numbering.html
  templates/dashboard/settings-reference-container.html
  templates/dashboard/settings-scrolling.html
  templates/dashboard/settings-start-end.html
  templates/public/footnote-alternative.html
  templates/public/footnote.html
  templates/public/js-reference-container.html
  templates/public/reference-container-body-3column.html
  templates/public/reference-container-body-combi.html
  templates/public/reference-container-body-switch.html
  templates/public/reference-container-body.html
  templates/public/reference-container.html
  templates/public/tooltip.html
Labels: bug

#38 Update code to comply with WP Coding Standards (third time's the charm!)
  .gitignore
  README.md
  _tools/setup.sh
  class/config.php
  class/convert.php
  class/dashboard/init.php
  class/dashboard/layout.php
  class/dashboard/subpage-diagnostics.php
  class/dashboard/subpage-main.php
  class/hooks.php
  class/init.php
  class/language.php
  class/layout/abstract-engine.php
  class/layout/diagnostics.php
  class/layout/init.php
  class/layout/settings.php
  class/settings.php
  class/task.php
  class/template.php
  class/widgets/base.php
  class/widgets/reference-container.php
  class/wysiwyg.php
  composer.json
  composer.lock
  contrib/pre-commit
  footnotes.php
  includes.php
  readme.txt
  templates/dashboard/other-plugins.html
  templates/public/footnote-alternative.html
Labels: documentation, duplicate, security

#49 Revert "Update code to comply with WP Coding Standards (third time's the charm!)"
  .gitignore
  README.md
  _tools/setup.sh
  class/config.php
  class/convert.php
  class/dashboard/init.php
  class/dashboard/layout.php
  class/dashboard/subpage-diagnostics.php
  class/dashboard/subpage-main.php
  class/hooks.php
  class/init.php
  class/language.php
  class/layout/abstract-engine.php
  class/layout/diagnostics.php
  class/layout/init.php
  class/layout/settings.php
  class/settings.php
  class/task.php
  class/template.php
  class/widgets/base.php
  class/widgets/reference-container.php
  class/wysiwyg.php
  composer.json
  composer.lock
  contrib/pre-commit
  footnotes.php
  includes.php
  readme.txt
  templates/dashboard/other-plugins.html
  templates/public/footnote-alternative.html
Labels: bug

#50 Update code to comply with WP Coding Standards (*fourth* time's the charm!)
  .gitignore
  README.md
  _tools/setup.sh
  class/config.php
  class/convert.php
  class/dashboard/init.php
  class/dashboard/layout.php
  class/dashboard/subpage-diagnostics.php
  class/dashboard/subpage-main.php
  class/hooks.php
  class/init.php
  class/language.php
  class/layout/abstract-engine.php
  class/layout/diagnostics.php
  class/layout/init.php
  class/layout/settings.php
  class/settings.php
  class/task.php
  class/template.php
  class/widgets/base.php
  class/widgets/reference-container.php
  class/wysiwyg.php
  composer.json
  composer.lock
  contrib/pre-commit
  css/dev-common.css
  css/dev-tooltips.css
  css/footnotes-alttbrpl0.min.css
  css/footnotes-alttbrpl1.min.css
  css/footnotes-alttbrpl2.min.css
  css/footnotes-alttbrpl3.min.css
  css/footnotes-jqttbrpl0.min.css
  css/footnotes-jqttbrpl1.min.css
  css/footnotes-jqttbrpl2.min.css
  css/footnotes-jqttbrpl3.min.css
  css/footnotes-nottbrpl0.min.css
  css/footnotes-nottbrpl1.min.css
  css/footnotes-nottbrpl2.min.css
  css/footnotes-nottbrpl3.min.css
  css/settings.css
  footnotes.php
  includes.php
  readme.txt
  templates/dashboard/other-plugins.html
  templates/public/footnote-alternative.html
Labels: documentation, duplicate
