Repository markcheret/footnotes, pull requests merged in 2021-04, with the labels that each got.

#66 Create dependabot.yml
  .github/dependabot.yml
Labels: security

#75 fix: fix bug that caused footnotes to not be processed
  class/task.php
  readme.txt
Labels: bug

#76 chore: add php-commitizen
  .distignore
  .php-commitizen.php
  CONTRIBUTING.md
  composer.json
  composer.lock
Labels: workflow

#78 chore: fix character misencodings
  class/dashboard/subpage-main.php
  readme.txt
Labels: bug

#84 fix: get PHP Composer GitHub Actions to pass
  .github/workflows/php.yml
  README.md
  composer.json
  composer.lock
Labels: workflow

#83 fix: add separate prod/dev cache-busters
  _tools/build.sh
  class/dashboard/layout.php
  class/init.php
  class/layout/abstract-engine.php
  footnotes.php
Labels: workflow

#94 chore: remove date info
  class/config.php
  class/convert.php
  class/dashboard/init.php
  class/dashboard/layout.php
  class/dashboard/subpage-diagnostics.php
  class/dashboard/subpage-main.php
  class/hooks.php
  class/init.php
  class/language.php
  class/layout/abstract-engine.php
  class/layout/diagnostics.php
  class/layout/init.php
  class/layout/settings.php
  class/settings.php
  class/task.php
  class/template.php
  class/widgets/base.php
  class/widgets/reference-container.php
  class/wysiwyg.php
  css/dev-common.css
  css/dev-layout-entry-content.css
  css/dev-layout-main-content.css
  css/dev-layout-reference-container.css
  css/dev-tooltips.css
  customized-documentation-schema.txt
  customized-template-stack.txt
  footnotes.php
  js/jquery.tools.js
  js/jquery.tools.min.js
  js/wysiwyg-editor.js
Labels: documentation

#98 sync with 2.7.0
  class/dashboard/layout.php
  class/dashboard/subpage-main.php
  class/hooks.php
  class/init.php
  class/layout/abstract-engine.php
  class/layout/settings.php
  class/settings.php
  class/task.php
  footnotes.php
  js/wysiwyg-editor.js
  readme.txt
  templates/dashboard/settings-reference-container.html
  templates/public/amp-footnote-expand.html
  templates/public/amp-footnote.html
Labels: bug, traceability

#93 build: add automated JS/CSS linting
  .eslintignore
  .eslintrc.js
  .github/workflows/php.yml
  .gitignore
  .prettierignore
  .prettierrc
  .stylelintignore
  .stylelintrc.json
  README.md
  composer.json
  composer.lock
  css/dev-amp-tooltips.css
  css/dev-common.css
  css/dev-tooltips-alternative.css
  css/dev-tooltips.css
  css/settings.css
  js/wysiwyg-editor.js
  package-lock.json
  package.json
Labels: workflow, wpcs-compliance

#105 build: add PHPCompatibility sniffs
  class/settings.php
  class/task.php
  composer.json
  composer.lock
  contrib/pre-commit
Labels: workflow

#110 Delete features.txt
  features.txt
Labels: workflow

#106 refactor: relocate Plugin settings
  class/dashboard/init.php
  class/dashboard/layout.php
  class/dashboard/subpage-diagnostics.php
  class/hooks.php
  class/layout/abstract-engine.php
  class/layout/diagnostics.php
  class/layout/init.php
  class/layout/settings.php
  contrib/pre-commit
  img/main-menu.png
  templates/dashboard/diagnostics.html
  templates/dashboard/manfisher.html
Labels: enhancement

#118 Fix paragraph separation
  class/task.php
Labels: bug

#120 docs: update readme and PHPDoc settings
  class/dashboard/subpage-main.php
  composer.json
  docs/classes/MCI-Footnotes-Config.html
  docs/classes/MCI-Footnotes-Convert.html
  docs/classes/MCI-Footnotes-Hooks.html
  docs/classes/MCI-Footnotes-Language.html
  docs/classes/MCI-Footnotes-Layout-Engine.html
  docs/classes/MCI-Footnotes-Layout-Init.html
  docs/classes/MCI-Footnotes-Layout-Settings.html
  docs/classes/MCI-Footnotes-LayoutEngine.html
  docs/classes/MCI-Footnotes-Settings.html
  docs/classes/MCI-Footnotes-Task.html
  docs/classes/MCI-Footnotes-Template.html
  docs/classes/MCI-Footnotes-WYSIWYG.html
  docs/classes/MCI-Footnotes-Widget-Base.html
  docs/classes/MCI-Footnotes-Widget-Reference-Container.html
  docs/classes/MCI-Footnotes.html
  docs/files/class-config.html
  docs/files/class-convert.html
  docs/files/class-dashboard-init.html
  docs/files/class-dashboard-layout.html
  docs/files/class-dashboard-subpage-main.html
  docs/files/class-hooks.html
  docs/files/class-init.html
  docs/files/class-language.html
  docs/files/class-settings.html
  docs/files/class-task.html
  docs/files/class-template.html
  docs/files/class-widgets-base.html
  docs/files/class-widgets-reference-container.html
  docs/files/class-wysiwyg.html
  docs/files/includes.html
  docs/index.html
  docs/indices/files.html
  docs/js/searchIndex.js
  docs/namespaces/default.html
  docs/packages/Default.html
  docs/packages/default.html
  docs/packages/footdnotes.html
  docs/packages/footnotes.html
  docs/reports/errors.html
  docs/reports/markers.html
  phpdoc.dist.xml
  readme.txt
Labels: documentation

#114 refactor: remove `MCI` prefixes
  .php-commitizen.php
  class/config.php
  class/convert.php
  class/dashboard/init.php
  class/dashboard/layout.php
  class/dashboard/subpage-main.php
  class/hooks.php
  class/init.php
  class/language.php
  class/settings.php
  class/task.php
  class/template.php
  class/widgets/base.php
  class/widgets/reference-container.php
  class/wysiwyg.php
  composer.json
  footnotes.php
Labels: documentation, invalid, wpcs-compliance

#127 ci: release process tweaks
  .github/workflows/release-handler.yml
  _tools/build-stylesheets.sh
  _tools/build.sh
  _tools/release.sh
  js/wysiwyg-editor.js
  readme.txt
Labels: bug, workflow

#131 ci: rename folder during release process
  .github/workflows/release-handler.yml
Labels: invalid, workflow

#130 security: add snyk
  .github/workflows/snyk.yml
  README.md
  package.json
Labels: documentation, security

#139 docs: update WP readme
  CHANGELOG.md
  footnotes.php
  readme.txt
Labels: documentation, workflow, wpcs-compliance

#144 release: release 2.7.3
  .github/img/footnotes.png
  .php-commitizen.php
  CHANGELOG.md
  README.md
  _tools/build.sh
  _tools/release.sh
  _tools/setup.sh
  contrib/pre-commit
  package.json
  src/class/wysiwyg.php
  src/footnotes.php
  src/js/wysiwyg-editor.js
  src/readme.txt
Labels: documentation, workflow

#149 ci: improve linting
  .distignore
  .eslintignore
  .eslintrc.js
  .github/workflows/lint-code.yml
  .github/workflows/ossar-analysis.yml
  .github/workflows/php.yml
  .github/workflows/pre-release.yml
  .github/workflows/snyk.yml
  .gitignore
  .htmlhintrc
  .prettierrc
  .stylelintignore
  .stylelintrc.json
  LICENSE
  LICENSE.md
  composer.json
  package-lock.json
  package.json
  phpdoc.dist.xml
  src/class/dashboard/layout.php
  src/class/dashboard/subpage-main.php
  src/class/init.php
  src/class/task.php
  src/class/wysiwyg.php
  src/css/dev-amp-tooltips.css
  src/css/dev-common.css
  src/css/dev-layout-entry-content.css
  src/css/dev-layout-main-content.css
  src/css/dev-layout-reference-container.css
  src/css/dev-tooltips-alternative.css
  src/css/dev-tooltips.css
  src/css/settings.css
  src/js/wysiwyg-editor.js
  src/templates/dashboard/other-plugins.html
  src/wpml-config.xml
Labels: dependencies, workflow, wpcs-compliance

#155 docs: amend code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#150 doc: update author url
  src/footnotes.php
  src/js/wysiwyg-editor.js
Labels: documentation

#164 chore: lint coc
  CODE_OF_CONDUCT.md
  README.md
Labels: workflow
