Repository markcheret/footnotes, pull requests merged in 2021-05, with the labels that each got.

#166 update snyk scan frequency
  .github/workflows/snyk.yml
Labels: security

#170 Add type declarations, increase minimum supported PHP version and add Rector dep
  _tools/build.sh
  _tools/deploy-dev.sh
  composer.json
  composer.lock
  rector.php
  src/README.txt
  src/admin/class-admin.php
  src/admin/class-wysiwyg.php
  src/admin/layout/class-engine.php
  src/admin/layout/class-init.php
  src/admin/layout/class-settings.php
  src/footnotes.php
  src/includes/class-activator.php
  src/includes/class-config.php
  src/includes/class-convert.php
  src/includes/class-core.php
  src/includes/class-deactivator.php
  src/includes/class-i18n.php
  src/includes/class-loader.php
  src/includes/class-settings.php
  src/includes/class-template.php
  src/public/class-general.php
  src/public/class-parser.php
  src/public/widget/class-base.php
  src/public/widget/class-reference-container.php
  src/uninstall.php
Labels: dependencies, documentation, enhancement, security, workflow

#173 docs: add donation link to GitHub repo
  .github/FUNDING.yml
Labels: documentation, enhancement

#177 Close #176
  package-lock.json
  package.json
Labels: dependencies
