Repository markcheret/footnotes, pull requests merged in 2021-03, with the labels that each got.

#54 Update version number to 2.5.11d0
  footnotes.php
  readme.txt
Labels: documentation, good first issue, invalid

#57 Sync filenames with SVN repo
  class/convert.php
  class/dashboard/init.php
  class/dashboard/layout.php
  class/dashboard/subpage-diagnostics.php
  class/dashboard/subpage-main.php
  footnotes.php
  includes.php
  readme.txt
Labels: compliance, traceability

#61 Fixcomments
  class/dashboard/layout.php
  class/init.php
  development/customized-documentation-schema.txt
  footnotes.php
  readme.txt
Labels: documentation, traceability

#62 Update supported WP version to 5.7
  footnotes.php
  readme.txt
Labels: compliance, documentation

#63 updated author URI
  class/dashboard/init.php
  footnotes.php
  js/wysiwyg-editor.js
Labels: documentation

#64 Add release helper script
  .gitignore
  README.md
  _tools/build-stylesheets.sh
  _tools/build.sh
  _tools/release.sh
  class/dashboard/layout.php
  class/init.php
  composer.json
  composer.lock
  css/tmp/footnotes-alttbrpl0.min.css
  css/tmp/footnotes-alttbrpl1.min.css
  css/tmp/footnotes-alttbrpl2.min.css
  css/tmp/footnotes-alttbrpl3.min.css
  css/tmp/footnotes-jqttbrpl0.min.css
  css/tmp/footnotes-jqttbrpl1.min.css
  css/tmp/footnotes-jqttbrpl2.min.css
  css/tmp/footnotes-jqttbrpl3.min.css
  css/tmp/footnotes-nottbrpl0.min.css
  css/tmp/footnotes-nottbrpl1.min.css
  css/tmp/footnotes-nottbrpl2.min.css
  css/tmp/footnotes-nottbrpl3.min.css
  css/tmp/settings.min.css
  footnotes.php
  js/wysiwyg-editor.js
  readme.txt
Labels: documentation, workflow
